# Generated by Django 3.2 on 2023-06-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('blog', models.TextField()),
                ('image', models.ImageField(upload_to='blogs_images/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('category_image', models.ImageField(null=True, upload_to='category_images/')),
                ('order', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Category',
            },
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category', models.CharField(max_length=100)),
                ('order', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Child Category',
            },
        ),
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='company_images/')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='partner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=10, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'percentage'), ('amount', 'amount')], default='percentage', max_length=100, null=True)),
                ('discount', models.IntegerField(null=True)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.category')),
            ],
            options={
                'verbose_name_plural': '2. Sub Category',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonial_images/')),
                ('company_name', models.CharField(max_length=100)),
                ('testimonial', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=1000)),
                ('template_details', models.TextField()),
                ('template_features', models.TextField()),
                ('template_layout', models.TextField()),
                ('template_price', models.IntegerField()),
                ('is_taxable', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20)),
                ('version', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=1000)),
                ('template_image', models.ImageField(blank=True, null=True, upload_to='template_images/')),
                ('template_url', models.URLField(blank=True, null=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='template_files/')),
                ('is_featured', models.BooleanField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.category')),
                ('child_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.childcategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='childcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.subcategory'),
        ),
    ]
